window.WINKTIMER_SLIDES = [
  {
    id: "timer",
    accent: "#18563f",
    tone: "green",
    badge: "WINK TIMER",
    eyebrow: "GENERAL TIMER",
    headline: "기본 타이머부터\n센서 모드까지",
    body: "버튼으로 바로 쓰는 기본 타이머에 시선, 윙크, 미소, 뒤집기 모드를 더했습니다.",
    footerTitle: "평범한 타이머처럼 시작",
    footerBody: "요리, 운동, 공부, 루틴 어디서나 바로 사용",
    layout: "modes",
    screenshots: [{ src: "assets/screenshots/modes.png", alt: "Wink Timer mode list" }],
    chips: ["BASIC", "LOOK", "WINK", "SMILE"],
  },
  {
    id: "look",
    accent: "#2f7ed8",
    tone: "blue",
    badge: "LOOK PAUSE",
    eyebrow: "FACE DIRECTION CONTROL",
    headline: "보면 멈추고\n시선을 돌리면 재개",
    body: "LOOK PAUSE는 얼굴 방향을 감지해 손대지 않고 타이머 흐름을 제어합니다.",
    footerTitle: "손을 쓰기 어려운 순간에",
    footerBody: "앞을 보면 멈춤, 다른 곳을 보면 재개",
    layout: "single",
    screenshots: [{ src: "assets/screenshots/look.png", alt: "Look Pause timer mode" }],
  },
  {
    id: "wink",
    accent: "#18563f",
    tone: "green",
    badge: "WINK CONTROL",
    eyebrow: "GESTURE TIMER",
    headline: "손이 바쁠 때\n윙크로 제어",
    body: "오른쪽·왼쪽 윙크로 시작, 일시정지, 재개, 리셋 액션을 실행할 수 있습니다.",
    footerTitle: "제스처로 움직이는 타이머",
    footerBody: "버튼을 누르기 어려울 때 간단한 윙크 컨트롤",
    layout: "single",
    screenshots: [{ src: "assets/screenshots/wink.png", alt: "Wink Control timer mode" }],
  },
  {
    id: "smile",
    accent: "#ac2b24",
    tone: "red",
    badge: "SMILE MODE",
    eyebrow: "SMILE CONTROL",
    headline: "미소로\n타이머 재개",
    body: "SMILE MODE는 미소를 감지해 일시정지된 타이머를 자연스럽게 다시 시작합니다.",
    footerTitle: "가벼운 표정 인식",
    footerBody: "재미있고 직관적인 핸즈프리 타이머 컨트롤",
    layout: "single",
    screenshots: [{ src: "assets/screenshots/smile.png", alt: "Smile Mode timer" }],
  },
  {
    id: "settings",
    accent: "#18563f",
    tone: "green",
    badge: "SETTINGS",
    eyebrow: "CUSTOMIZE",
    headline: "언어와 감도까지\n내 방식대로",
    body: "알림, 카메라 분석, 앱 표시 언어를 한 곳에서 조정할 수 있습니다.",
    footerTitle: "설정은 한 곳에서",
    footerBody: "타이머 알림부터 언어 선택까지 빠르게 변경",
    layout: "dual",
    screenshots: [
      { src: "assets/screenshots/settings.png", alt: "Wink Timer settings" },
      { src: "assets/screenshots/language.png", alt: "Wink Timer language settings" },
    ],
  },
];
